### ISSUE TITLE
Error after collection of raw file statistics

### ISSUE THREAD

**Issue by jw-houghton** [Nesvilab/diaTracer#3]
I am receiving an error after the collection of raw file statistics when using my own data acquired on a timsTOF HT:

> 2024-06-10 16:50:56 [INFO] - Start
> Finished diff.
> Smallest IM diff is 5.015407361605995E-4
> Smallest MZ diff is 0.0026186111462038753
> Biggest IM is 1.3006687222513997
> Biggest MZ is 1700.0051890849998
> Smallest IM is 0.8505053316550746
> Smallest MZ is 100.00054169094568
> MS1 scan number is 2750
> MS2 scan number is 22000
> 2024-06-10 16:51:09 [INFO] - Collected raw file statistics in 13.41 s
> java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200
> 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
> 	at o.b(Unknown Source)
> 	at diatracer.diaTracerMainClass.a(Unknown Source)
> 	at diatracer.diaTracerMainClass.a(Unknown Source)
> 	at diatracer.diaTracerMainClass.<init>(Unknown Source)
> 	at diatracer.diaTracerMainClass.main(Unknown Source)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1200 out of bounds for length 1200
> 	at o.a(Unknown Source)
> 	at o.b(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

I am using a default fragpipe workflow and enabling diaTracer using default settings. When using the demo data, diaTracer works without error.

Many thanks for producing this tool!

**Comment by fcyu** [comment]
Same issue as https://github.com/Nesvilab/FragPipe/issues/1623

Best,

Fengchao
